apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: example-topic
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 3
  kafkaClusterRef:
    name: kafka
  configs:
    min.insync.replicas: "2"
    retention.ms: "86400000"